---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chuckchen.
---

--- 数组，就是相同数据类型的元素按一定顺序排列的集合，可以是一维数组和多维数组。
--- Lua 数组的索引键值可以使用整数表示，数组的大小不是固定的。


---array 如果指定索引没有值则返回nil
array = {"Lua", "Tutorial"}
for i = 0, 2 do
    print(array[i])
end

---array 可以使用负数作为索引
for i=-2, 2 do
    array[i] = i*2
end

for i=-2, 2 do
    print(i, array[i])
end


---array 多维数组
array = {}
for i=1, 3 do
    array[i] = {}
    for j=1, 3 do
        array[i][j] = i*j
    end
end

for i =1, 3 do
    for j=1, 3 do
        print(array[i][j])
    end
end


