---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chuckchen.
---

---function 可以多返回值
s, e = string.find("www.runoob.com", "runoob")
print(s, e)

function max(tab)
    local idx = 1
    local val = tab[1]
    for i, v in pairs(tab) do
        if v > val then
            idx = i
            val = v
        end
    end
    return idx, val
end
print(max({1,3,4,5,2,10}))


---function 可以接收可变参数
function average1(...)
    local sum = 0
    local arg = {...} ---将参数放入arg这个table
    for i, v in pairs(arg) do
        sum = sum + v
    end
    print("total num: "..#arg)
    return sum/#arg
end
print(average1(1,3,5,7,9))


---function 也可以通过select("#",...) 来获取可变参数的数量
---select('#', …) 返回可变参数的长度。
---select(n, …) 用于返回从起点 n 开始到结束位置的所有参数列表。
function average2(...)
    local sum = 0
    local arg = {...} ---将参数放入arg这个table
    for i, v in pairs(arg) do
        sum = sum + v
    end
    print("total num: "..select("#",...))
    return sum/#arg
end
print(average2(1,3,5,7,9))

function select_demo(...)
    for i = 1, select("#", ...) do
        local arg = select(i, ...)
        print("arg", arg)
    end
end
select_demo(1,2,3,4,5)


---function 参数可以为固定参数+可变参数的形式
function fwrite(fmt, ...)
    return io.write(string.format(fmt, ...))
end
print(fwrite("chuckchen\n"))
print(fwrite("%d%d", 1, 2))

