---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chuckchen.
---


--- 对于自定义的模块，模块文件不是放在哪个文件目录都行，函数 require 有它自己的文件路径加载策略，它会尝试从 Lua 文件或 C 程序库中加载模块。
--- require 用于搜索 Lua 文件的路径是存放在全局变量 package.path 中，当 Lua 启动后，会以环境变量 LUA_PATH 的值来初始这个环境变量。如果没有找到该环境变量，则使用一个编译时定义的默认路径来初始化。
--- 当然，如果没有 LUA_PATH 这个环境变量，也可以自定义设置

-- 测试module包
require("module")
print(module.constant)
module.func3()


-- 可以使用别名m来代表module
local m = require("module")
print(m.constant)
m.func3()

